# Generated by Django 4.1 on 2023-11-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_place_x_place_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='content_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
