# Generated by Django 4.1 on 2023-11-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_place_content_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='small_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
